#ifndef VOLUMERENDERER_GLOBAL_H
#define VOLUMERENDERER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VOLUMERENDERER_LIB
# define VOLUMERENDERER_EXPORT Q_DECL_EXPORT
#else
# define VOLUMERENDERER_EXPORT Q_DECL_IMPORT
#endif

#endif // VOLUMERENDERER_GLOBAL_H
