#ifndef WRFINTERPOLATIONSOLVER_GLOBAL_H
#define WRFINTERPOLATIONSOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WRFINTERPOLATIONSOLVER_LIB
# define WRFINTERPOLATIONSOLVER_EXPORT Q_DECL_EXPORT
#else
# define WRFINTERPOLATIONSOLVER_EXPORT Q_DECL_IMPORT
#endif

#endif // WRFINTERPOLATIONSOLVER_GLOBAL_H
